services:
  - type: web
    name: realestate-hub-ai
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: VAPI_PRIVATE_KEY
        value: 7b7f8428-c731-43c8-b2fa-6c6ceb847cc4
      - key: VAPI_PUBLIC_KEY
        value: 9efb9bb5-3fcf-439e-becf-f98742ab98d4
      - key: VAPI_ASSISTANT_ID
        value: 5b8807b3-1e6d-4a38-b1ba-25715f349899
      - key: DB_BACKEND
        value: sqlite
