"""Configuration and constants for Week 8 Day 4: Model Serving, AI Assistant & Integration.
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Dict, List, Any

# Base Directories
SRC_DIR = Path(__file__).resolve().parent
DAY4_DIR = SRC_DIR.parent
WEEK8_DIR = DAY4_DIR.parent

DATA_DIR = DAY4_DIR / "data"
MODELS_DIR = DAY4_DIR / "models"
REPORTS_DIR = DAY4_DIR / "reports"
FIGURES_DIR = REPORTS_DIR / "figures"
FIGURES_DIR.mkdir(parents=True, exist_ok=True)
ARCHITECTURE_DIR = DAY4_DIR / "architecture"
RANDOM_STATE = 42

# Database & Audit Paths
AUDIT_DB_PATH = DATA_DIR / "audit_logs.db"
AUDIT_LOG_JSONL = DATA_DIR / "prediction_audit.jsonl"
SIMULATED_EMAILS_LOG = DATA_DIR / "simulated_emails.log"

# Datasets with fallback to Day 2 and Day 3
PROPERTIES_DATASET_PATH = (
    (DATA_DIR / "properties_featured.csv")
    if (DATA_DIR / "properties_featured.csv").exists()
    else (WEEK8_DIR / "Day 2" / "data" / "properties_featured.csv")
)
LEADS_DATASET_PATH = (
    (DATA_DIR / "leads_featured.csv")
    if (DATA_DIR / "leads_featured.csv").exists()
    else (WEEK8_DIR / "Day 3" / "data" / "leads_featured.csv")
)
BATCH_SAMPLE_PROPERTIES_PATH = DATA_DIR / "batch_sample_properties.csv"
BATCH_SAMPLE_LEADS_PATH = DATA_DIR / "batch_sample_leads.csv"

# Model Artifacts
BEST_VALUATION_MODEL_PATH = MODELS_DIR / "best_valuation_model.joblib"
VALUATION_PREPROCESSOR_PATH = MODELS_DIR / "fitted_preprocessor.joblib"
QUANTILE_LOWER_MODEL_PATH = MODELS_DIR / "quantile_lower_model.joblib"
QUANTILE_UPPER_MODEL_PATH = MODELS_DIR / "quantile_upper_model.joblib"

BEST_LEAD_MODEL_PATH = MODELS_DIR / "best_lead_scoring_model.joblib"
LEAD_PREPROCESSOR_PATH = MODELS_DIR / "lead_preprocessor.joblib"
KMEANS_PERSONAS_MODEL_PATH = MODELS_DIR / "kmeans_personas_model.joblib"
PERSONA_SCALER_PATH = MODELS_DIR / "persona_scaler.joblib"

# Versioning & Metadata
API_VERSION = "1.0.0"
VALUATION_MODEL_VERSION = "v1.2.0-lgbm-quantile"
LEAD_MODEL_VERSION = "v1.1.0-lgbm-smote"
VALUATION_TRAINED_DATE = "2026-09-28"
LEAD_TRAINED_DATE = "2026-09-29"

# Vapi Live Voice Agent Telephony Credentials
VAPI_PUBLIC_KEY = os.getenv("NEXT_PUBLIC_VAPI_PUBLIC_KEY", "9efb9bb5-3fcf-439e-becf-f98742ab98d4")
VAPI_ASSISTANT_ID = os.getenv("VAPI_ASSISTANT_ID", "8b0b4889-a60f-404d-8e68-ed8afd91f7db")

# Legal Disclaimer
LEGAL_DISCLAIMER = (
    "Disclaimer: All property valuations, price ranges, and lead conversion scores are algorithmic "
    "statistical estimates generated by machine learning models based on historical transaction data. "
    "They do not constitute certified legal appraisals, mortgage valuations, or guaranteed financial outcomes."
)

# Supported Categoricals
VALID_CITIES = ["Lahore", "Islamabad", "Karachi", "Rawalpindi"]
VALID_PROPERTY_TYPES = ["House", "Flat", "Upper Portion", "Lower Portion", "Farm House", "Penthouse"]
VALID_LEAD_SOURCES = ["call", "WhatsApp", "Facebook", "website", "walk-in"]
VALID_PURPOSES = ["buy", "rent", "invest"]

# Operational Thresholds
HOT_THRESHOLD = 0.70
WARM_THRESHOLD = 0.35

# Out-of-Distribution (OOD) Guardrail Limits
OOD_LIMITS = {
    "min_area_marla": 1.0,
    "max_area_marla": 100.0,
    "min_bedrooms": 1,
    "max_bedrooms": 15,
    "min_bathrooms": 1,
    "max_bathrooms": 15,
    "min_age_years": 0,
    "max_age_years": 60,
    "min_floors": 1,
    "max_floors": 6,
    "min_price_pkr": 500_000.0,
    "max_price_pkr": 600_000_000.0,
    "min_budget_pkr": 500_000.0,
    "max_budget_pkr": 800_000_000.0,
    "min_number_of_calls": 1,
    "max_number_of_calls": 25,
    "min_call_duration_sec": 0,
    "max_call_duration_sec": 7200,
    "min_response_time_min": 0.0,
    "max_response_time_min": 1440.0,
}

# Society Tiers Dictionary (from Day 1)
SOCIETY_TIERS = {
    "DHA Phase 5": "Tier 1 Prime",
    "DHA Phase 6": "Tier 1 Prime",
    "DHA Phase 8": "Tier 1 Prime",
    "Gulberg III": "Tier 1 Prime",
    "Model Town": "Tier 1 Prime",
    "Cantt": "Tier 1 Prime",
    "F-6": "Tier 1 Prime",
    "F-7": "Tier 1 Prime",
    "F-8": "Tier 1 Prime",
    "F-10": "Tier 1 Prime",
    "DHA Defence": "Tier 1 Prime",
    "Clifton": "Tier 1 Prime",
    "Johar Town": "Tier 2 Mid",
    "Bahria Town": "Tier 2 Mid",
    "Faisal Town": "Tier 2 Mid",
    "F-11": "Tier 2 Mid",
    "E-11": "Tier 2 Mid",
    "G-11": "Tier 2 Mid",
    "DHA Phase 2": "Tier 2 Mid",
    "Bahria Town Islamabad": "Tier 2 Mid",
    "Bahria Town Phase 7": "Tier 2 Mid",
    "Bahria Town Phase 8": "Tier 2 Mid",
    "Chaklala Scheme 3": "Tier 2 Mid",
    "Gulshan-e-Iqbal": "Tier 2 Mid",
    "Township": "Tier 3 Budget",
    "Madina Colony": "Tier 3 Budget",
    "College Road": "Tier 3 Budget",
    "G-13": "Tier 3 Budget",
    "G-15": "Tier 3 Budget",
    "I-10": "Tier 3 Budget",
    "Ghauri Town": "Tier 3 Budget",
    "Airport Housing Society": "Tier 3 Budget",
    "North Nazimabad": "Tier 3 Budget",
    "Korangi": "Tier 3 Budget",
}
DEFAULT_SOCIETY_TIER = "Tier 2 Mid"

# Historical Society Benchmark Rates for 10-Marla standard units (PKR)
SOCIETY_BENCHMARK_PRICE = {
    "F-6": 55_000_000,
    "F-7": 52_000_000,
    "F-8": 48_000_000,
    "F-10": 42_000_000,
    "F-11": 38_000_000,
    "E-11": 26_000_000,
    "G-11": 24_000_000,
    "G-13": 21_000_000,
    "G-15": 16_000_000,
    "I-10": 15_000_000,
    "DHA Phase 2": 28_000_000,
    "Bahria Town Islamabad": 22_000_000,
    "Ghauri Town": 11_000_000,
    "DHA Phase 5": 45_000_000,
    "DHA Phase 6": 42_000_000,
    "DHA Phase 7": 32_000_000,
    "DHA Phase 8": 36_000_000,
    "Gulberg III": 48_000_000,
    "Model Town": 44_000_000,
    "Cantt": 39_000_000,
    "Johar Town": 27_000_000,
    "Bahria Town": 23_000_000,
    "Faisal Town": 26_000_000,
    "Township": 16_000_000,
    "College Road": 15_000_000,
    "Madina Colony": 14_000_000,
    "Bahria Town Phase 7": 24_000_000,
    "Bahria Town Phase 8": 21_000_000,
    "Airport Housing Society": 18_000_000,
    "Chaklala Scheme 3": 28_000_000,
    "DHA Defence": 46_000_000,
    "Clifton": 49_000_000,
    "Gulshan-e-Iqbal": 22_000_000,
    "North Nazimabad": 17_000_000,
    "Korangi": 9_000_000,
}

# Production Metrics Benchmark Summary
VALUATION_METRICS = {
    "mae_pkr": 1_420_000,
    "mae_lac": 14.2,
    "rmse_crore": 0.28,
    "r2_score": 0.891,
    "mape_pct": 5.4,
    "quantile_coverage_pct": 82.6,
}

LEAD_METRICS = {
    "precision_at_top20": 0.824,
    "roc_auc": 0.912,
    "pr_auc": 0.748,
    "f1_score": 0.795,
    "balanced_accuracy": 0.841,
    "hot_lead_conversion_rate": 0.812,
}


def format_price_pkr(price_pkr: float) -> str:
    """Format numeric PKR into conversational Pakistani Crore / Lac string."""
    if price_pkr is None or price_pkr <= 0:
        return "N/A"
    if price_pkr >= 10_000_000:
        crores = price_pkr / 10_000_000.0
        return f"{crores:.2f} crore"
    else:
        lacs = price_pkr / 100_000.0
        return f"{lacs:.1f} lac"


# Ensure directories exist
DATA_DIR.mkdir(parents=True, exist_ok=True)
MODELS_DIR.mkdir(parents=True, exist_ok=True)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)
ARCHITECTURE_DIR.mkdir(parents=True, exist_ok=True)
